---
name: Build Kernel Package

# yamllint disable-line rule:truthy
on:
  [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: 'Checkout repo'
        uses: actions/checkout@v2
      - name: 'Set up Python 3.9'
        uses: actions/setup-python@v2
      - name: 'Install dependencies'
        run: |
          python -m pip install --upgrade pip
          pip install yamllint
          sudo apt-get install shellcheck bash
      - name: 'Analysing the code'
        run: |
          yamllint .
          shellcheck ./*.sh
  build:
    needs: [lint]
    runs-on: ubuntu-20.04
    steps:
      - name: 'Checkout Repo'
        uses: actions/checkout@v2

      - name: Build script
        id: build
        run: |
          mkdir /tmp/artifacts
          UREL=$(grep ^UBUNTU_REL build.sh | head -n1 | cut -d = -f2)
          PREL=$(grep "PKGREL=\d*" build.sh | cut -d = -f2)
          sudo ./build.sh
          cd /home/work/linux-kernel
          VERSION=$(make kernelversion)
          echo Built $VERSION-$UREL-hwe-$PREL
          echo "::set-output name=tag::${VERSION}-${UREL}-hwe-${PREL}"
          cd /tmp/artifacts
          ls -l
          dpkg-scanpackages . /dev/null | gzip -9c > Packages.gz
          ls -l

      - name: Upload package artifact
        uses: actions/upload-artifact@v2
        with:
          name: linux-T2-Mojave-${{ steps.build.outputs.tag }}
          path: /tmp/artifacts/*

      - name: Release
        if: github.ref == 'refs/heads/HWE-5.13'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            /tmp/artifacts/Packages.gz
            /tmp/artifacts/sha256
            /tmp/artifacts/*.deb
          tag_name: v${{ steps.build.outputs.tag }}
          body: linux-headers must be installed before linux-image.
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
